# Generated by Django 6.0.1 on 2026-06-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_ti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='setor',
        ),
    ]
