# Generated by Django 6.0.1 on 2026-06-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_ti', '0002_remove_equipamento_setor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ['categoria', 'nome']},
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='descricao',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='categoria',
            field=models.CharField(choices=[('perifericos', 'Periféricos (Mouse, Teclado...)'), ('hardware', 'Hardware / Computadores (Desktop, Notebook...)'), ('rede', 'Rede & Conectividade (Roteador, Switch...)'), ('suprimentos', 'Suprimentos & Impressão (Impressora, Scanner...)')], default='perifericos', max_length=30),
        ),
        migrations.AddField(
            model_name='setor',
            name='equipamentos',
            field=models.ManyToManyField(blank=True, related_name='setores', to='chamados_ti.equipamento'),
        ),
    ]
