# Generated by Django 6.0.1 on 2026-06-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_ti', '0003_alter_equipamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
