# Generated by Django 6.0.1 on 2026-06-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_ti', '0004_equipamento_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='descricao',
        ),
    ]
