# Generated by Django 6.0.1 on 2026-06-29 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_ti', '0005_remove_equipamento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='chamados_ti.setor'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='categoria',
            field=models.CharField(choices=[('perifericos', 'Periféricos'), ('hardware', 'Hardware / Computadores'), ('rede', 'Rede & Conectividade'), ('suprimentos', 'Suprimentos & Impressão')], default='perifericos', max_length=30),
        ),
    ]
