# Generated by Django 6.0.1 on 2026-07-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_ti', '0006_chamado_setor_alter_equipamento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
