# Generated by Django 6.0.1 on 2026-07-13 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_ti', '0009_mensagemchamado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='chamados_ti.setor'),
            preserve_default=False,
        ),
    ]
