# Generated by Django 6.0.1 on 2026-07-30 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_ti', '0010_alter_chamado_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'Um usuário com este nome já existe.'}, help_text='Obrigatório. Até 150 caracteres. Letras, números e espaços são permitidos.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\s@\\.\\+\\-_]+$', 'Informe um nome de usuário válido. Pode conter letras, números, espaços e os caracteres @/./+/-/_.')], verbose_name='nome de usuário'),
        ),
    ]
