# Generated by Django 6.0.1 on 2026-08-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_ti', '0011_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemchamado',
            name='imagem',
            field=models.FileField(upload_to='chamados/'),
        ),
    ]
