# Generated by Django 6.0.1 on 2026-08-06 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_ti', '0012_alter_imagemchamado_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemchamado',
            name='mensagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='chamados_ti.mensagemchamado'),
        ),
    ]
