# Generated by Django 6.0.1 on 2026-08-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_ti', '0013_imagemchamado_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='previsao_atendimento',
            field=models.DateField(blank=True, help_text='Data estimada para início do atendimento.', null=True, verbose_name='Previsão de Atendimento'),
        ),
    ]
