# Generated by Django 6.0.1 on 2026-08-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_ti', '0014_chamado_previsao_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='previsao_atendimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Previsão de Atendimento'),
        ),
    ]
