# Generated by Django 6.0.1 on 2026-08-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_ti', '0015_alter_chamado_previsao_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='forcar_troca_senha',
            field=models.BooleanField(default=False, verbose_name='Forçar troca de senha no próximo login'),
        ),
    ]
